export const LANGUAGES = [
  { code: "en", name: "English", flag: "🇬🇧", rtl: false },
  { code: "ar", name: "العربية", flag: "🇸🇦", rtl: true },
  { code: "fr", name: "Français", flag: "🇫🇷", rtl: false },
  { code: "ur", name: "اردو", flag: "🇵🇰", rtl: true },
  { code: "es", name: "Español", flag: "🇪🇸", rtl: false },
  { code: "sw", name: "Kiswahili", flag: "🇹🇿", rtl: false },
];

export const GRADES = [
  { id: "elementary", label: "Elementary", ages: "Ages 6–10", desc: "Simple language, hands-on examples" },
  { id: "middle", label: "Middle School", ages: "Ages 11–14", desc: "Developing concepts, real-world links" },
  { id: "high", label: "High School", ages: "Ages 15–17", desc: "Abstract thinking, complex analysis" },
];

export const COUNTRIES = [
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", region: "Middle East" },
  { code: "AE", name: "UAE", flag: "🇦🇪", region: "Middle East" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", region: "Middle East" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", region: "Middle East" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", region: "Middle East" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", region: "Middle East" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", region: "Middle East" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", region: "Middle East" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", region: "Africa" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", region: "Africa" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", region: "Africa" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", region: "Africa" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", region: "Africa" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", region: "Africa" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", region: "Africa" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", region: "Africa" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", region: "Africa" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", region: "South Asia" },
  { code: "IN", name: "India", flag: "🇮🇳", region: "South Asia" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", region: "South Asia" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", region: "South Asia" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", region: "South Asia" },
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", region: "South Asia" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", region: "Southeast Asia" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", region: "Southeast Asia" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", region: "Southeast Asia" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", region: "Southeast Asia" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", region: "Southeast Asia" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", region: "Southeast Asia" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", region: "Southeast Asia" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", region: "Latin America" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", region: "Latin America" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", region: "Latin America" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", region: "Latin America" },
  { code: "PE", name: "Peru", flag: "🇵🇪", region: "Latin America" },
  { code: "CL", name: "Chile", flag: "🇨🇱", region: "Latin America" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", region: "Latin America" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", region: "Latin America" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", region: "Latin America" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", region: "Latin America" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", region: "Caribbean" },
  { code: "HT", name: "Haiti", flag: "🇭🇹", region: "Caribbean" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", region: "Caribbean" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", region: "Caribbean" },
  { code: "TT", name: "Trinidad & Tobago", flag: "🇹🇹", region: "Caribbean" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", region: "Central Asia" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", region: "Central Asia" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", region: "Central Asia" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", region: "Central Asia" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", region: "Central Asia" },
];

export const SUBJECTS = [
  { name: "Mathematics", icon: "Sigma", color: "#f59e0b" },
  { name: "Chemistry", icon: "FlaskConical", color: "#a855f7" },
  { name: "Biology", icon: "Leaf", color: "#22c55e" },
  { name: "Physics", icon: "Atom", color: "#06b6d4" },
  { name: "History", icon: "ScrollText", color: "#3b82f6" },
  { name: "Geography", icon: "Globe2", color: "#10b981" },
  { name: "Economics", icon: "TrendingUp", color: "#ef4444" },
  { name: "Ethics", icon: "Scale", color: "#ec4899" },
  { name: "Environmental Science", icon: "TreePine", color: "#84cc16" },
  { name: "Social Studies", icon: "Users", color: "#f97316" },
  { name: "Media Literacy", icon: "Newspaper", color: "#8b5cf6" },
  { name: "Cultural Studies", icon: "Palette", color: "#c9a84c" },
];

export const subjectColor = (name: string): string => {
  const s = SUBJECTS.find((x) => x.name.toLowerCase() === name.toLowerCase());
  return s?.color ?? "#7c3aed";
};
