/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SparkRouteImport } from './routes/spark'
import { Route as RawiRouteImport } from './routes/rawi'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIdRouteImport } from './routes/library.$id'

const SparkRoute = SparkRouteImport.update({
  id: '/spark',
  path: '/spark',
  getParentRoute: () => rootRouteImport,
} as any)
const RawiRoute = RawiRouteImport.update({
  id: '/rawi',
  path: '/rawi',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRouteWithChildren
  '/rawi': typeof RawiRoute
  '/spark': typeof SparkRoute
  '/library/$id': typeof LibraryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRouteWithChildren
  '/rawi': typeof RawiRoute
  '/spark': typeof SparkRoute
  '/library/$id': typeof LibraryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRouteWithChildren
  '/rawi': typeof RawiRoute
  '/spark': typeof SparkRoute
  '/library/$id': typeof LibraryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/library'
    | '/rawi'
    | '/spark'
    | '/library/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/library'
    | '/rawi'
    | '/spark'
    | '/library/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/explore'
    | '/library'
    | '/rawi'
    | '/spark'
    | '/library/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  RawiRoute: typeof RawiRoute
  SparkRoute: typeof SparkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spark': {
      id: '/spark'
      path: '/spark'
      fullPath: '/spark'
      preLoaderRoute: typeof SparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rawi': {
      id: '/rawi'
      path: '/rawi'
      fullPath: '/rawi'
      preLoaderRoute: typeof RawiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryIdRoute: typeof LibraryIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryIdRoute: LibraryIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRouteWithChildren,
  RawiRoute: RawiRoute,
  SparkRoute: SparkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
