/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SparkRouteImport } from './routes/spark'
import { Route as IndexRouteImport } from './routes/index'

const SparkRoute = SparkRouteImport.update({
  id: '/spark',
  path: '/spark',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spark': typeof SparkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spark': typeof SparkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spark': typeof SparkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spark'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spark'
  id: '__root__' | '/' | '/spark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SparkRoute: typeof SparkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spark': {
      id: '/spark'
      path: '/spark'
      fullPath: '/spark'
      preLoaderRoute: typeof SparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SparkRoute: SparkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
